name: Documentation

on:
  push:
    branches: [main, master]

jobs:
  make-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: select python version
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .
          python -m pip install sphinx
          python -m pip install sphinx_rtd_theme
          python -m pip install sphinx-click
          python -m pip install nbsphinx
          python -m pip install nbsphinx>=0.9.2
          python -m pip install sphinxcontrib.mermaid>==0.9.2
          python -m pip install sphinx-autoapi>=2.1.1
          python -m pip install sphinx-copybutton>=0.5.0
          python -m pip install myst-parser>=2.0.0
          python -m pip install furo>=2023.7.26
          python -m pip install jupyter-black>=0.3.4
          python -m pip install sphinxcontrib.bibtex>=2.6.2
          python -m pip install sphinx-gallery
      - name: build documentation
        run: |
          cd docs
          make html
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
          force_orphan: true
          full_commit_message: ${{ github.event.head_commit.message }}
